### ISSUE TITLE
Needs a command line

### ISSUE THREAD

**Issue by RPeschke** [AlbertoPdRF/root-file-viewer#16]
Hi,

very nice addon! really enjoy using it but i think it could benefit from having a command line to use  the usual commands for plotting 2 branches of a tree or set filters etc.  

```cpp
tree->Draw("y:x","sector==1","colz");
```
something like that.

thanks,
Richard

**Comment by AlbertoPdRF** [comment]
Hey @RPeschke!

Please note that this can already be done by right-clicking on the tree, selecting "Draw > player", and entering the desired expression. All supported features can be seen at https://github.com/root-project/jsroot/blob/master/docs/JSROOT.md#ttree-draw.

**Comment by RPeschke** [comment]
Hi,

thank you for the answer. just tried it works like a charm. 

thanks for you work!
