### ISSUE TITLE
Add option to show tab bar again

### ISSUE THREAD

**Issue by dnwerner** [AlbertoPdRF/root-file-viewer#17]
First of all: Thanks for the great update! Unfortunately despite many nice changes, the update removed the tab bar showing the currently open histograms - unfortunately just switching between histograms in "simple" view doesn't preserve zoom etc., so this is a functional regression for some workflows.

**Comment by AlbertoPdRF** [comment]
Hey @dnwerner!

In addition to what @olifre already mentioned, please note that you can keep using v0.6.0 until a new version is released after https://github.com/root-project/jsroot/issues/238 is addressed :slightly_smiling_face:

**Comment by AlbertoPdRF** [comment]
This has been addressed in 3f8dad9676664953cf374d88555f639bfe107dcf, and will be included in a release soon :rocket:
