### ISSUE TITLE
Add re-binning functionality

### ISSUE THREAD

**Issue by dnwerner** [AlbertoPdRF/root-file-viewer#2]
The extension is an awesome tool to improve productivity.

A few features from the TBrowser that are helpful are still missing: One of these is the option to re-bin the viewed histograms (analogous to the Re-bin function in the TBrowser, just suming up existing bins).

**Comment by AlbertoPdRF** [comment]
Hey @dnwerner!

First of all, thanks for your kind words and for openning the issues! And also sorry for the delay in getting back to you.

Regarding this issue, it's important to note that ROOT File Viewer leverages the [JavaScript ROOT package](https://github.com/root-project/jsroot) to do all the heavy lifting, and after taking a look I don't think it supports rebinning histograms 😕 I could be wrong though, maybe @linev can enlighten us!

**Comment by linev** [comment]
Yes, histograms rebinning has to be implemented in JSROOT directly.
You could open issue on project https://github.com/root-project/jsroot webpage
It should be not that difficult - there much complex functions like:
https://root.cern/js/latest/examples.htm#th2_projx1

**Comment by AlbertoPdRF** [comment]
I've just opened https://github.com/root-project/jsroot/issues/210 @linev, thanks for the very quick reply!

**Comment by AlbertoPdRF** [comment]
Please note that although https://github.com/root-project/jsroot/issues/210 has already been addressed (albeit not released yet) this issue is still blocked by #6

**Comment by linev** [comment]
One can call rebin via sub-menu, but also I will try to find better solution than using `prompt`

**Comment by AlbertoPdRF** [comment]
Oh, that's very nice! I'll close the issue when the re-binning functionality is included in a JSROOT release, thanks for letting me know!

**Comment by linev** [comment]
Now in jsroot 6.1.0 jquery dialog is used instead of prompt

**Comment by AlbertoPdRF** [comment]
Yep, I'm already publishing `v0.3.0` with all the changes, thanks for the heads up! :slightly_smiling_face:

**Comment by dnwerner** [comment]
@linev @AlbertoPdRF Thank you! (sorry to tag you, but your work is really helping!)
