### ISSUE TITLE
Windows with long names have hidden minimize/maximize/close buttons

### ISSUE THREAD

**Issue by schwas3** [AlbertoPdRF/root-file-viewer#21]
I love using this extension for debugging and there are quite long branch names involved and I have found that the wrapping (at least so I believe) prioritizes the window name over these three buttons, making it hidden completely or barely visible (functionally limiting the size of the button to a very small height). Since there is no right click and close or shortcut to close this can be a bit of a time waster, having to click the window bar and hope the "close" button becomes visible just so I can grab the very small region (another process that isn't all that easy) just to closer a window. By increasing the width of the window so that the entire name fits, it resolves the problem. A fix in one of the future releases would be great! Thanks for developing this extension!

![image](https://user-images.githubusercontent.com/80727263/179573910-08a08ef8-2e54-4ba6-bb0e-ce8802a1d2b1.png)

![image](https://user-images.githubusercontent.com/80727263/179573789-02e22443-8877-44c0-85a7-0a1df57d075c.png)

![image](https://user-images.githubusercontent.com/80727263/179574161-d40cef52-d715-4c9f-9d1c-26fb63ed8fdd.png)

**Comment by schwas3** [comment]
User-workaround: right click in the background (i.e. outside of the space of any of the open windows) and select to minimize all, you should now be able to select to close windows easily

**Comment by AlbertoPdRF** [comment]
Hi @schwas3!

Thanks for filling the issue! Could you please check if this is still a problem with [v1.0.0](https://github.com/AlbertoPdRF/root-file-viewer/releases/tag/v1.0.0)?

**Comment by schwas3** [comment]
@AlbertoPdRF I'd say this issue no longer applies to v1.0.0, here is what long branch name handling looks like now:

![image](https://user-images.githubusercontent.com/80727263/184193779-80b52791-656f-4f90-aa08-08fda40795a5.png)

One thing I will note as I close this issue, is that having more than one canvas open is not possible and it is not possible to split VSCode windows to open a second instance of the same .root file, so even that does not allow for such interaction. Also there is a new issue I am going to create about the "Enlarge Canvas" functionality but that is not relevant to this issue...

**Comment by AlbertoPdRF** [comment]
You cannot open more than one canvas because the default layout has been changed back to `tabs`, which is the one that has always been the default except for `v0.7.0` and `v0.8.0`. You can go back to the `flex` layout by adjusting the relevant extension setting if you prefer it :slightly_smiling_face:
