### ISSUE TITLE
Enlarge Canvas, Can still see TBrowser navigator overlayed with canvas

### ISSUE THREAD

**Issue by schwas3** [AlbertoPdRF/root-file-viewer#22]
Steps to reproduce:

Open a file in VSCode using rfv
Open a histogram or other grahpic
Use the `Enlarge canvas` option on the bottom left options
![image](https://user-images.githubusercontent.com/80727263/184194457-60f8606c-83ff-447f-8538-bc989d83f697.png)
Before enlarging:
![image](https://user-images.githubusercontent.com/80727263/184194976-39017a29-b733-40d5-9585-f1b350dc10df.png)
After enlarging:
![image](https://user-images.githubusercontent.com/80727263/184194891-b6922eb1-59c2-45b6-b5a1-ede8afffbf72.png)

On the left, the TBrowser navigator (for lack of a better term) can still be seen behind the canvas, as if the canvas has some kind of transparency setting.

**Comment by AlbertoPdRF** [comment]
I can see this also happening when JSROOT is running standalone (see https://jsroot.gsi.de/latest/api.htm#custom_html_file_browser,) so maybe this is the intended behaviour. CCing @linev so he can tell us.

**Comment by linev** [comment]
Yes, it is intended. 
Enlarged canvas is by 10% opaque.
