### ISSUE TITLE
zooming in 2D hitogramm doesn't update color scale

### ISSUE THREAD

**Issue by AelSandro** [AlbertoPdRF/root-file-viewer#23]
When opening a 2D histogram and zooming in, the color scale does not update to the minimal and maximal counts of visible bins, making it difficult to see structures.
In the TBrowser this does work.

**Comment by AlbertoPdRF** [comment]
Hi! I'm not able to replicate this problem, could you share a video or something so I can see what you mean?

**Comment by AelSandro** [comment]
Thank you, but the latest release seems to have fixed the issue (cannot reproduce it after updating).
