### ISSUE TITLE
Lack of draw same option

### ISSUE THREAD

**Issue by PuttyDeVil** [AlbertoPdRF/root-file-viewer#24]
How to draw two histogram in the same canvas? In the latest web version of JSROOT 7.4, I can drag another histogram into an existing canvas, but this function doesn't work in the vscode extension. I find this extension is using the JSROOT 7.2.0 now. Is this problem from the difference of versions?

**Comment by AlbertoPdRF** [comment]
Hi! I didn't know this feature existed. I just tried in my local machine after upgrading JSROOT to v7.4.0 and it still doesn't work. This is the error I see in the developer console:

![Error](https://github.com/AlbertoPdRF/root-file-viewer/assets/26309166/a29181cb-a831-423d-b110-3563655d4cd1)

Maybe @linev knows what the error is about?

**Comment by linev** [comment]
I cannot reproduce problem with plain JSROOT in web browser.
Probably something differs in VS code.

**Comment by PuttyDeVil** [comment]
Thank you very much!  Hope more convenient functions can be used in VS code in the future.

> Hi! I didn't know this feature existed. I just tried in my local machine after upgrading JSROOT to v7.4.0 and it still doesn't work. This is the error I see in the developer console:
> 
> ![Error](https://user-images.githubusercontent.com/26309166/251109048-a29181cb-a831-423d-b110-3563655d4cd1.png)
> 
> Maybe @linev knows what the error is about?

**Comment by linev** [comment]
> Hi! I didn't know this feature existed. I just tried in my local machine after upgrading JSROOT to v7.4.0 and it still doesn't work. This is the error I see in the developer console:
> 
> ![Error](https://user-images.githubusercontent.com/26309166/251109048-a29181cb-a831-423d-b110-3563655d4cd1.png)
> 
> Maybe @linev knows what the error is about?

I found a reason for the bug. Fix is very simple.
I can publish it in 7.4.1 release.

**Comment by linev** [comment]
Draw same will be available in next jsroot release.
It is in the current master already, but release is far away.

**Comment by AlbertoPdRF** [comment]
Thank you for the info! I will make sure to upgrade JSROOT's version as soon as it comes out :slightly_smiling_face:
