### ISSUE TITLE
When Nans are stored in TBranch, VS code does not display the branch at all

### ISSUE THREAD

**Issue by abhijitm08** [AlbertoPdRF/root-file-viewer#25]
When a `TBranch` has a value of `Nan` stored (due to failing fits, etc), VS code does not display the branch at all. 

![Screenshot 2023-07-24 at 13 27 36](https://github.com/AlbertoPdRF/root-file-viewer/assets/9482011/08ecd804-b1d6-44d0-bd39-4eb73b2deb8f)

To get around this one has to apply a cut `TRUEPT != TMath::QuiteNan()`. 

![Screenshot 2023-07-24 at 13 37 19](https://github.com/AlbertoPdRF/root-file-viewer/assets/9482011/cfcf4cf7-0b4a-43ea-acbe-75e7e6155622)

I believe this is not an issue when plotting with plain ROOT TBrowser but when displaying within VS code. 

Would appreciate it if this could be fixed.

**Comment by AlbertoPdRF** [comment]
Hi @abhijitm08 and thanks for opening the issue! Could you provide a sample ROOT File so I can reproduce this? Thanks!

**Comment by abhijitm08** [comment]
@AlbertoPdRF Thank you for the quick response. The ROOT file is at the [CERN box](https://cernbox.cern.ch/s/nrLDk5MNy9xWfa6). I just noticed that the CERN box ROOT viewer has the same behaviour as VS code browser. 

When I do: `tree->Draw("Branch1")`, I get:

![Screenshot 2023-07-24 at 15 09 34](https://github.com/AlbertoPdRF/root-file-viewer/assets/9482011/7b0d82f7-3488-405d-aa15-7ddc2347bf90)

When I open `TBrowser t`, I get: 

![Screenshot 2023-07-24 at 15 16 57](https://github.com/AlbertoPdRF/root-file-viewer/assets/9482011/b0f9c228-c0b8-429b-a669-a7f5ab4b278c)

In VS code and the CERN box ROOT viewer I get: 

![Screenshot 2023-07-24 at 15 09 40](https://github.com/AlbertoPdRF/root-file-viewer/assets/9482011/0177d09e-1580-4f19-847a-2a79013ad59b)

**Comment by AlbertoPdRF** [comment]
I can also replicate the issue online in https://jsroot.gsi.de/latest/api.htm#url_syntax_open_file, so I'm CC'ing @linev.

**Comment by linev** [comment]
Yes, `NaN` values where not handled correctly with TTree::Draw. 
Now fixed in `dev` and `7.4` branch.

**Comment by abhijitm08** [comment]
> Yes, `NaN` values where not handled correctly with TTree::Draw. Now fixed in `dev` and `7.4` branch.

Thank you for the reply. Would be awesome if this gets fixed in the new release of `root-file-viewer`.

**Comment by linev** [comment]
Now available with https://github.com/root-project/jsroot/releases/tag/7.4.2 release

**Comment by AlbertoPdRF** [comment]
Awesome @linev! I'll publish a release with JSROOT v7.4.2 soon 🚀
