### ISSUE TITLE
A problem with display a log funciton in a fit via extension

### ISSUE THREAD

**Issue by skipperglume** [AlbertoPdRF/root-file-viewer#26]
When opening a histogram with a fit, which expression contains a log function, the curve is drawn incorrectly. Same histo drawn and saved in root code displays a correct fit curve. Here are two images, one made from extension and standard Draw() method. 

![extension_problematic_display_log_fit](https://github.com/AlbertoPdRF/root-file-viewer/assets/100448836/76316fee-2151-4ab1-bfe7-693f7fae9c1c)

![using_standard_root_draw](https://github.com/AlbertoPdRF/root-file-viewer/assets/100448836/026eca89-56dd-4d26-9c6b-6d951c4bac94)

**Comment by AlbertoPdRF** [comment]
Hi @skipperglume, thanks for opening the issue! Could you please provide a ROOT File so I can try to reproduce it? Thanks!

**Comment by skipperglume** [comment]
Hi @AlbertoPdRF !
Here are both the .root file and a code to Draw() all histo in a 'plots' folder. Run it with simple 'root test.cxx' command. 
https://github.com/skipperglume/Draw_Utensils/tree/main/logProblem

I use both Windows and Ubuntu, and have the problem on both setups.

**Comment by AlbertoPdRF** [comment]
Thanks @skipperglume! As I can also replicate the issue on https://jsroot.gsi.de/latest/api.htm#url_syntax_open_file, I'm CC'ing @linev

**Comment by linev** [comment]
Yes, I can confirm problem.
Fixed by https://github.com/root-project/jsroot/commit/cd7f1612234688b7bbcdb2b2f72dcb7edf5a1747

Will be released later today with `7.4.2` version

**Comment by AlbertoPdRF** [comment]
Thanks again @linev! 🎉
