### ISSUE TITLE
Add fit-tool integration

### ISSUE THREAD

**Issue by dnwerner** [AlbertoPdRF/root-file-viewer#4]
Thanks for the great project! If possible could you add a rudimentary fit tool akin to the TBrowser-included tool (might be out of scope / technically impossible)?

**Comment by AlbertoPdRF** [comment]
And thanks for this issue too, @dnwerner!

I originally thought about adding a command to the extension that opens an integrated `TBrowser` and let's you do everything that you would expect, but I don't think this is possible with [JavaScript ROOT](https://github.com/root-project/jsroot) -- maybe @linev can let us know if there are any plans to support the `TBrowser` class within `JSROOT`?

**Comment by linev** [comment]
No - fitting will require rewriting a lot of code, which is implemented in ROOT.
Therefore in such case one have to install and use ROOT directly

**Comment by AlbertoPdRF** [comment]
Thanks for another very quick reply and for the info @linev!

@dnwerner I'm going to close this issue as it indeed seems to be out of scope
