### ISSUE TITLE
Modals from JS ROOT aren't being displayed

### ISSUE THREAD

**Issue by AlbertoPdRF** [AlbertoPdRF/root-file-viewer#6]
I just noticed that modals (e.g. `prompt`) aren't working, so all [JavaScript ROOT](https://github.com/root-project/jsroot) functionality that uses them (e.g. setting an axis range) isn't working either.

Related: https://github.com/Microsoft/vscode/issues/67109

**Comment by linev** [comment]
For rebinning there are several values in sub-menu which can be selected without input prompt.
But one could think of some other alternative - I create issue https://github.com/root-project/jsroot/issues/216 as reminder.

**Comment by AlbertoPdRF** [comment]
That would be awesome @linev, let me know if I can help in any way!
