### ISSUE TITLE
Extension makes a large amount of files when installing

### ISSUE THREAD

**Issue by cparker24** [AlbertoPdRF/root-file-viewer#9]
My home directory is limited to 10k files, and even if I make sure I have room for 7k, I still cannot install the extension. It maxes out what my directory can hold even if I remove all the data I can. Is there a way to install it that doesn't have this issue?

**Comment by AlbertoPdRF** [comment]
Hey @cparker24!

After 30d0a72037badd3c64f4705efc58385a1ed6f62b, which is included in [v0.7.0](https://github.com/AlbertoPdRF/root-file-viewer/releases/tag/v0.7.0), this should be solved!
